<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">



  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="0.3" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.15" />
  <xacro:property name="base_length" value="0.3" />
  <xacro:property name="base_height" value="0.12" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.040" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="caster_wheel_mass" value="0.1" /> <!-- arbitrary value for caster wheel mass -->
  <xacro:property name="caster_wheel_radius" value="0.05" />
  <xacro:property name="z_offset" value="-${base_height/2}" /> <!-- Space btw top of beam and the each joint -->

  <!-- Base Link -->
  <link name="base_link">
  </link>

  <!-- BASE_FOOTPRINT LINK -->
  <joint name="base_footprint_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint">
  </link>


  <!-- Chassis Link -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="-0.1 0 0"/>
  </joint>

  <link name="chassis">
    <visual>
        <origin xyz="${base_length/2} 0 ${base_height/2}"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="white"/>
    </visual>
    <collision>
          <origin xyz="${base_length/2} 0 ${base_height/2}"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
    </collision>
    <xacro:inertial_box mass="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}">
      <origin xyz="${base_length/2} 0 ${base_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
  </link>

  <gazebo reference="chassis">
      <material>Gazebo/Green</material>
  </gazebo>


  <!-- left wheel Link -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${base_width/2 + wheel_len/2} 0" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="left_wheel">
      <material>Gazebo/Black</material>
  </gazebo>


  <!-- right wheel Link -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${base_width/2 + wheel_len/2} 0" rpy="${PI/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="right_wheel">
      <material>Gazebo/Black</material>
  </gazebo>


  <!-- caster rear wheel Link -->
  <joint name="caster_rear_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_rear_wheel"/>
    <origin xyz="0.25 0 0"/>
  </joint>

  
  <link name="caster_rear_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:inertial_sphere mass="0.1" radius="${caster_wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_sphere>
  </link>

  <gazebo reference="caster_rear_wheel">
    <material>Gazebo/White</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>

</robot>